"""Fix appointment-user relationship and cascade delete

Revision ID: 15725d100ced
Revises: 88b42a001803
Create Date: 2025-07-16 01:06:29.841689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15725d100ced'
down_revision = '88b42a001803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aadhar', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.String(length=20), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('dob')
        batch_op.drop_column('aadhar')

    # ### end Alembic commands ###
