"""Add delivery_option to appointment

Revision ID: c8d15eeaa94f
Revises: 15725d100ced
Create Date: 2025-07-17 12:56:12.857556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d15eeaa94f'
down_revision = '15725d100ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_option', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('delivery_option')

    # ### end Alembic commands ###
