"""Add reschedule_count to appointment

Revision ID: efeb43d2679c
Revises: c8d15eeaa94f
Create Date: 2025-07-18 09:18:33.632342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efeb43d2679c'
down_revision = 'c8d15eeaa94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reschedule_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('reschedule_count')

    # ### end Alembic commands ###
